# SPDX-License-Identifier: CC0-1.0
# Copyright © 2026      GSI Helmholtzzentrum fuer Schwerionenforschung GmbH
#                       Matthias Kretz <m.kretz@gsi.de>
repos:
  - repo: local
    hooks:
      - id: reuse-lint
        name: reuse lint-file
        entry: reuse lint-file
        language: system
        pass_filenames: true
