# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright © 2025–2026 GSI Helmholtzzentrum fuer Schwerionenforschung GmbH
#                       Matthias Kretz <m.kretz@gsi.de>

objdir = obj

CXXFLAGS+=-std=c++26 -Wall -Wextra -Werror -O2 -g0 -Wno-attributes -D_GLIBCXX_ASSERTIONS=1 \
	  -D_GLIBCXX_SIMD_COND_EXPLICIT_MASK_CONVERSION -DVIR_PATCH_PERMUTE_DYNAMIC \
	  -DVIR_PATCH_MATH -DVIR_PATCH_TEST_STORES -DVIR_ASSERT_SANITY -DVIR_PATCH_IMPROVE_CX=3 \
	  $(FLAGS)
CXXFLAGS_clang := -Wno-unknown-pragmas -ferror-limit=3
CXXFLAGS_gcc := -fconcepts-diagnostics-depth=2 -fconstexpr-ops-limit=67108864 -fmax-errors=6 \
		-freflection -Wno-psabi -static-libstdc++ -fno-operator-names

cxx_version := $(shell $(CXX) --version | head -n1)

ifneq ($(findstring clang,$(cxx_version)),)
compiler:=clang
ifeq ($(CLANG_GCC_TOOLCHAIN),)
CLANG_GCC_TOOLCHAIN := $(shell for p in ~/.local/gcc*/bin/g++ /usr/local/bin/g++* /usr/bin/g++*; do \
		       [ -x "$$p" ] || continue; \
		       ver=$$($$p -dumpversion); \
		       [ "$${ver%%.*}" -ge 16 ] || continue; \
		       datestr=$$($$p --version | head -n1 | grep -oE '[0-9]{8}'); \
		       echo "$$ver $$datestr $$p"; \
		       done | sort -rV -k1,1 -k2,2r | head -n1 | cut -d' ' -f3)
endif
ifneq ($(CLANG_GCC_TOOLCHAIN),)
CXXFLAGS_clang += --gcc-toolchain=$(abspath $(shell $(CLANG_GCC_TOOLCHAIN) -print-prog-name=cc1plus | sed 's,/libexec/gcc/.*/cc1plus$$,,'))
else
$(warning No GCC >= 16 found for clang. Set CLANG_GCC_TOOLCHAIN to a suitable g++ path.)
endif
else ifneq ($(findstring g++,$(cxx_version))$(findstring GCC,$(cxx_version)),)
compiler:=gcc
CXXFLAGS_clang += --gcc-toolchain=$(abspath $(shell $(CXX) -print-prog-name=cc1plus | sed 's,/libexec/gcc/.*/cc1plus$$,,'))
else
compiler:=unknown
endif

ifneq ($(SIMD_OBJ_SUBST),)
ifneq ($(objdir),obj)
$(error Ambiguous instructions: both 'objdir' and 'SIMD_OBJ_SUBST' are set to non-default values)
endif
real_obj_dir=$(shell echo $(CURDIR)|sed '$(SIMD_OBJ_SUBST)')
make_obj_dir_rule := mkdir -p $(real_obj_dir)/check && ln -sf $(real_obj_dir) $(objdir)
else
make_obj_dir_rule := mkdir -p $(objdir)/check
endif

ifeq ($(file < $(objdir)/.cxx_version),)
unused:=$(or $(shell $(make_obj_dir_rule) && echo ok),$(error "Failed to set up objdir: $(make_obj_dir_rule)"))
$(shell test -w check || ln -sf $(objdir)/check check)
$(file > $(objdir)/.cxx_version,$(cxx_version))
else
ifneq ($(file < $(objdir)/.cxx_version),$(cxx_version))
$(info Remove PCH because the compiler changed from "$(file < $(objdir)/.cxx_version)" to "$(cxx_version)". $(shell rm -f $(objdir)/*.hpp.gch))
$(file > $(objdir)/.cxx_version,$(cxx_version))
endif
endif

print_compiler_info:
	@echo "Compiler: $(CXX) $(ICECC_CXX)"
	@echo "          $(cxx_version)"
ifeq ($(compiler),clang)
	@echo "GCC Toolchain: $(CLANG_GCC_TOOLCHAIN)"
endif
	@echo "-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-"

CXXFLAGS += $(CXXFLAGS_$(compiler))

#-D_GLIBCXX_DEBUG_UB=1

ifeq ($(ICECC_CXX),)
LINK_CXX := $(CXX)
else
LINK_CXX := $(ICECC_CXX)
endif

ifeq ($(notdir $(realpath $(CXX))),distcc)
# using distcc
ifeq ($(shell $(realpath $(CXX)) --show-hosts),)
# except, not really
DIRECT := 1
endif

else ifeq ($(notdir $(realpath $(CXX))),icecc)
# using icecc
ifeq ($(ICECC),no)
DIRECT := 1
else ifeq ($(ICECC),disable)
DIRECT := 1
else ifneq ($(DIRECT),)
ifneq ($(ICECC_CXX),)
# with icecream, DIRECT, and ICECC_CXX set, and CXX resolving to icecc, compile
# locally but allocate slots on the icecream scheduler
export ICECC=no
endif
endif

else
# CXX isn't using icecream or distcc
DIRECT := 1
endif

NUM_JOBS = $(patsubst -j%,%,$(filter -j%,$(MAKEFLAGS)))

testarchs ::= x86-64 \
	     x86-64-v2 \
	     ivybridge \
	     x86-64-v3 \
	     x86-64-v4 \
	     graniterapids

ifeq ($(FLAGS),-m32)
testarchs += i686 pentium3
endif

disabled_tests ::=

tests ::= $(filter-out $(disabled_tests),$(patsubst tests/%.cpp,%,$(wildcard tests/*.cpp)))

int_tests ::= $(foreach t,$(tests),\
	$(if $(shell grep -E '// *requires (float|complex)' tests/$(t).cpp),,$(t)))

float_tests ::= $(foreach t,$(tests),\
	$(if $(shell grep -E '// *requires (int|complex)' tests/$(t).cpp),,$(t)))

complex_tests ::= $(foreach t,$(tests),\
	$(if $(shell grep -E '// *requires (int|float)' tests/$(t).cpp),,$(t)))

fast_math_tests ::= $(foreach t,$(tests),\
	$(if $(shell grep -E '// no-fast-math' tests/$(t).cpp),,$(t)))

int_testtypes ::= \
	signed-char \
	unsigned-char \
	signed-short \
	unsigned-short \
	signed-int \
	unsigned-int \
	signed-long-long \
	unsigned-long-long

float_testtypes ::= \
	double \
	float

complex_testtypes ::= \
	complex-double \
	complex-float

ifneq ($(FLAGS),-m32)
ifneq ($(compiler),clang)
float_testtypes += float16_t
complex_testtypes += complex-float16_t
endif
endif

testtypes ::= \
	$(int_testtypes) \
	$(float_testtypes) \
	$(complex_testtypes)

testtypes ::= $(subst ::,--,$(testtypes))

testwidths ::= $(shell seq 1 64)

testtypes_for_test = $(if $(filter $(1),$(complex_tests)),$(complex_testtypes),) \
		     $(if $(filter $(1),$(float_tests)),$(float_testtypes),) \
		     $(if $(filter $(1),$(int_tests)),$(int_testtypes),)

getwidth = $(subst .,,$(suffix $(1)))
gettype = $(subst -, ,$(subst complex-double,std::complex<double>,$(subst complex-float,std::complex<float>,$(subst complex-float16_t,std::complex<float16_t>,$(subst .,,$(basename $(notdir $(1))))))))
getarch = $(subst .,,$(suffix $(subst /,,$(dir $(1)))))
gettest = $(basename $(subst /,,$(dir $(1))))

ifneq ($(MAKE_TERMOUT),)
CXXFLAGS += -fdiagnostics-color=always
msg_build := \e[34;1mBuild\e[0m
msg_link  := \e[33;1mLink \e[0m
msg_run   := \e[32;1mRun✔️ \e[0m
msg_runf  := \e[31;1mRun❌\e[0m
else
msg_build := Build:
msg_link  := Link :
msg_run   := Run :)
msg_runf  := Run :(
endif

diag_transform := sed -e 's/std::simd::_ArchFlags{[^{}]*}/_ArchFlags/g' \
		      -e 's/std::simd::_OptFlags{[^{}]*}/_OptFlags/g' \
		      -e 's/std::simd::_TargetTraits{[^{}]*}/_TargetTraits/g' \
		      -e 's/\<std::simd::/simd::/g'
#diag_transform := cat

define call_compiler
{ { $(CXX) $(1) 2>&1; echo $$?>&2; } | $(diag_transform); } 3>&2 2>&1 1>&3 | { read s; [ $$s -gt 0 ] && echo Build command was: $(CXX) $(1); exit $$s; }
endef

print_progress := true

.PHONY: setup_progress
setup_progress:

$(objdir)/%.fast-math.hpp: $(objdir)/%.hpp
	@cp $< $@

define pch_template
$(objdir)/$(1).hpp: tests/unittest*.h tests/*.cpp
	@echo "Generate $$@"
	@grep -h '^ *# *include ' tests/unittest*.h tests/*.cpp|grep -v unittest.h|sed 's,","$(CURDIR)/tests/,' > $$@

$(objdir)/$(1).depend: $(objdir)/$(1).hpp
	@echo "Update $(1) dependencies"
	@$$(CXX) $$(CXXFLAGS) -march=$(1) -MM -MT "$(objdir)/$(1).hpp" $(objdir)/$(1).hpp | sed 's, $(objdir)/$(1).hpp ,,' > $$@

include $(objdir)/$(1).depend

$(objdir)/$(1).hpp.gch: $(objdir)/$(1).hpp | print_compiler_info
	@printf -- '$$(msg_build) pre-compiled header for $(1)\n'
	@$$(call call_compiler, $$(CXXFLAGS) -march=$(1) -c $$< -o $$@)

$(objdir)/$(1).fast-math.hpp.gch: $(objdir)/$(1).fast-math.hpp | print_compiler_info
	@printf -- '$$(msg_build) pre-compiled fast-math header for $(1)\n'
	@$$(call call_compiler, $$(CXXFLAGS) -ffast-math -march=$(1) -c $$< -o $$@)

endef

$(foreach arch,$(testarchs),\
	$(eval $(call pch_template,$(arch))))

#	@driver.sh $(1) $(2) $$* "$(DIRECT)" "$$(CXX)" "$$(LINK_CXX)" $$(CXXFLAGS)
# arguments: test, arch
define exe_template
$(objdir)/$(3)$(1).$(2)/%.o: tests/$(1).cpp $(objdir)/$(2).$(3)hpp tests/unittest*.h | $(objdir)/$(2).$(3)hpp.gch setup_progress
	@printf -- '$$(msg_build)   $$@\n'
	@mkdir -p $$(dir $$@)
	@rm -f $$(@:%.o=%.exe) $$@
	@./wait_for_memory.sh "$$(NUM_JOBS)"
	@$$(call call_compiler,$$< -march=$(2) -DUNITTEST_TYPE="$$(call gettype,$$*)" -DUNITTEST_WIDTH=$$(call getwidth,$$*) $$(CXXFLAGS)$(4) -include $(objdir)/$(2).$(3)hpp -c -o $$@)

$(objdir)/$(3)$(1).$(2)/%.exe: $(objdir)/$(3)$(1).$(2)/%.o $(objdir)/libsimd.a
	@printf -- '$$(msg_link) $$@\n'
	@$$(LINK_CXX) $$(CXXFLAGS)$(4) -march=$(2) -o $$@ $$(@:%.exe=%.o) $(objdir)/libsimd.a

check/$(3)$(1).$(2)/%: $(objdir)/$(3)$(1).$(2)/%.exe
	@mkdir -p $$(dir $$@)
	@rm -f $$@.failed
	@$$(SIM) $$(@:check/%=$(objdir)/%.exe) >$$@ 2>&1 && { \
		printf -- '$$(msg_run) %-60s %s\n' '$$@' "$$$$($$(print_progress))"; \
		touch -r $$(@:check/%=$(objdir)/%.exe) $$@; \
	} || { \
		printf -- '$$(msg_runf) $$@\n'; \
		cat $$@; \
		mv $$@ $$@.failed; \
		false; \
	}

endef

$(foreach arch,$(testarchs),\
	$(foreach t,$(tests),\
	$(eval $(call exe_template,$(t),$(arch),,)))\
	$(foreach t,$(fast_math_tests),\
	$(eval $(call exe_template,$(t),$(arch),fast-math., -ffast-math))))

constexpr_checks ::= $(foreach arch,$(testarchs),$(objdir)/constexpr.$(arch).s $(objdir)/math-traits.$(arch).s) $(objdir)/generic-traits.s

.PHONY: check-constexpr
check-constexpr: $(shell shuf -e -- $(constexpr_checks))

check_targets := $(objdir)/check.targets

codegen_files ::= $(wildcard codegen/*.c++)
codegen_names ::= $(patsubst codegen/%.c++,%,$(codegen_files))
codegen_targets ::= $(patsubst %,check-codegen-%,$(codegen_names))

check-codegen: $(codegen_targets)

$(objdir)/codegen.depend: $(objdir) $(codegen_files)
	@echo "Update codegen dependencies ..."
	$(file >$@)
	$(foreach c,$(codegen_names),\
	  $(shell $(CXX) $(CXXFLAGS) -MM -MT $(objdir)/codegen.$c.s codegen/$c.c++ >> $@))

include $(objdir)/codegen.depend

$(objdir)/constexpr.%.s: $(objdir)/%.hpp.gch constexpr_tests.cpp
	@printf -- '$(msg_build) constexpr tests for $*\n'
	@$(call call_compiler, $(CXXFLAGS) -march=$* -include $(objdir)/$*.hpp -S -o $@ constexpr_tests.cpp)

$(objdir)/math-traits.%.s: math-traits_tests.cpp $(objdir)/%.hpp.gch
	@printf -- '$(msg_build) math traits tests for $*\n'
	@$(call call_compiler, $(CXXFLAGS) -march=$* -include $(objdir)/$*.hpp -S -o $@ $<)

$(objdir)/generic-traits.s: generic-traits_tests.cpp include/bits/simd_details.h
	@printf -- '$(msg_build) generic traits tests\n'
	@$(call call_compiler, $(CXXFLAGS) -S -o $@ $<)

.PHONY: always-remake
always-remake: ;

check-codegen-%: $(objdir)/codegen.%.s codegen/check.sh
	@echo "Testing for expected instructions in $<"
	@codegen/check.sh "codegen/$*.c++" "$<"

$(objdir)/codegen.%.s: codegen/%.c++ $(objdir)
	@echo "Building $@"
	@$(CXX) $(CXXFLAGS) -masm=intel -march=skylake -fcf-protection=none -S -o $@ $<
	@cat $@ | grep -v '^\s*\.' | c++filt > $@.tmp
	@mv $@.tmp $@

clean-outdated-%:
	@name="$(firstword $(subst ., ,$*))"; \
	arch="$(lastword $(subst ., ,$*))"; \
	for f in check/$$name.$$arch/*.*; do \
		if [ $$f -ot tests/$*.cpp ] || \
			[ $$f -ot $(objdir)/$$arch.hpp ] || \
			[ $$f -ot tests/unittest.h ]; then \
			echo "Remove $$f"; \
			rm $$f; \
		fi; \
	done

.PHONY: clean-outdated
clean-outdated: $(foreach t,$(tests),$(foreach a,$(testarchs),clean-outdated-$(t).$(a)))
	@echo "No outdated check/*.*/*.* files are left."
