# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright © 2025      GSI Helmholtzzentrum fuer Schwerionenforschung GmbH
#                       Matthias Kretz <m.kretz@gsi.de>

name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  gcc:
    strategy:
      fail-fast: false
      matrix:
        version: [14]

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install GCC ${{ matrix.version }}
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y gcc-${{ matrix.version }} g++-${{ matrix.version }}

      - name: Run test suite
        env:
          CXX: g++-${{ matrix.version }}
        run: make -j2 check-constexpr check/simd_bit.ivybridge/unsigned-short.39 check/simd_alg.core2/signed-int.9 check/arithmetic.skylake/float.41

  clang:
    strategy:
      fail-fast: false
      matrix:
        version: [20]

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Install Clang ${{ matrix.version }}
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
          sudo add-apt-repository 'deb http://apt.llvm.org/noble/ llvm-toolchain-noble-${{ matrix.version }} main'
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y g++-14 clang-${{ matrix.version }}
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 110 --slave /usr/bin/g++ g++ /usr/bin/g++-14

      - name: Run test suite
        env:
          CXX: clang++-${{ matrix.version }}
        run: make -j2 check-constexpr check/arithmetic.skylake/float.41
